image: "python:3.8"

before_script:
  - python -v                                   # Print out Python version for debugging
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt


stages:
  - test
  
test_job:
  stage: test
  image: "python:3.8"
  script:
    - python setup.py test
